### PR TITLE
Fix: If cgroup manager is cgroupfs then allow conmon_cgroup to be empty

### LINKED ISSUE #6047: crio fails validation for conmon_cgroup when using cgroupfs as cgroup manager
### What happened?

`crio` fails validation for `conmon_cgroup` when using `cgroupfs` as cgroup manager. With following configuration:

    [crio.runtime]
    cgroup_manager = "cgroupfs"
    conmon_cgroup = ""

Due to presence of conflicting checks a97c66840e119656066510970dd2f214032ce527 and 211902f5a1b5d560804aafabe77a92509191dda5, the only acceptable value is `pod`.

Otherwise it would fail with:

    level=fatal msg="Validating runtime config: conmon cgroup should be 'pod' or a systemd slice"

OR:

    level=fatal msg="Validating runtime config: cgroupfs manager conmon cgroup should be 'pod' or empty"

### What did you expect to happen?

Validation to pass

### How can we reproduce it (as minimally and precisely as possible)?

Start crio with following configuration:

    [crio.runtime]
    cgroup_manager = "cgroupfs"
    conmon_cgroup = ""

And crio will fail validation.

### Anything else we need to know?

_No response_

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.21.7
Version:       1.21.7
GitCommit:     283ec410c082bf91304bbf6f5d5bf1c6490a0e3d
GitTreeState:  dirty
BuildDate:     1980-01-01T00:00:00Z
GoVersion:     go1.15.7
Compiler:      gc
Platform:      linux/amd64
Linkmode:      static
```

I assume you probably meant `kubelet --version` in the following

```console
$ kubectl --version
Kubernetes v1.21.6
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux example.com 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

### PR DESCRIPTION
**Pull request by xw19**
conmon_cgroup is deprecated and is replaced with RuntimeHandler monitor_cgroup and we prepopulate with default 'system.slice'

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:
Fixes #6047 

#### Does this PR introduce a user-facing change?
None

```release-note
Fixes #6047
```

### CODE REVIEW

File: pkg/config/config.go [hunk 1]
```diff
@@ -874,6 +874,50 @@ func (c *Config) ToBytes() ([]byte, error) {
 	return buffer.Bytes(), nil
 }
 
+// DefaultRuntimeConfig returns the default Runtime configss.
```
Comment (roman-kiselenko) [inline pkg/config/config.go:877]:
```suggestion
// DefaultRuntimeConfig returns the default Runtime config.
```

**Review by roman-kiselenko — APPROVED** [review]

File: pkg/config/config.go [hunk 2]
```diff
@@ -239,8 +238,9 @@ type RuntimeHandler struct {
 	// Fields prefixed by Monitor hold the configuration for the monitor for this runtime. At present, the following monitors are supported:
 	// oci supports conmon
 	// vm does not support any runtime monitor
-	MonitorPath   string   `toml:"monitor_path,omitempty"`
-	MonitorCgroup string   `toml:"monitor_cgroup,omitempty"`
+	MonitorPath string `toml:"monitor_path,omitempty"`
+	// MonitorCgroup should allow empty value in case of cgroupfs
```
Comment (kwilczynski) [inline pkg/config/config.go:242]: Not sure if this comment adds value.

**Review by roman-kiselenko — APPROVED** [review]

File: pkg/config/config.go [hunk 3]
```diff
@@ -240,7 +239,7 @@ type RuntimeHandler struct {
 	// oci supports conmon
 	// vm does not support any runtime monitor
 	MonitorPath   string   `toml:"monitor_path,omitempty"`
-	MonitorCgroup string   `toml:"monitor_cgroup,omitempty"`
+	MonitorCgroup string   `toml:"monitor_cgroup"`
```
[the remark this answers is not in the document]
Comment (xw19) [reply pkg/config/config.go]: Added back

**Comment by saschagrunert** [comment]
@sohankunkerkar please rebase

**Comment by saschagrunert** [comment]
@xw19 please rebase this one

File: pkg/config/config.go [hunk 4]
```diff
@@ -890,6 +889,50 @@ func (c *Config) ToBytes() ([]byte, error) {
 	return buffer.Bytes(), nil
 }
 
+// DefaultRuntimeConfig returns the default Runtime configs.
+func DefaultRuntimeConfig(cgroupManager cgmgr.CgroupManager) *RuntimeConfig {
```
Comment (haircommander) [inline pkg/config/config.go:893]: nit: can this be defined below where it's callled?

**Comment by haircommander** [comment]
/approve

LGTM, @cri-o/cri-o-maintainers PTAL

**Review by sohankunkerkar — APPROVED** [review]
/lgtm
