### PR TITLE
OCPBUGS-81547: oci: wait for exit file before defaulting to exit code 255

### LINKED ISSUE #9840: CRI-O reports exit code 255 for fast-exiting init containers in production (conmon race condition)
### What happened?

CRI-O intermittently reports exit code 255 for containers that exit very quickly (<10ms), even though the container process completed successfully.

CRI-O logs show:
```
level=error msg="Failed to update container state for a0b136050c270...: stdout: , stderr: "
```

This is a re-report of #8980 which was closed without a fix. Unlike #8980 which only affected e2e tests, this issue is a **production blocker** — multiple production environments are experiencing random container failures with no error logs and no user-actionable information.

### What did you expect to happen?

Containers that exit with code 0 should have exit code 0 reported by CRI-O, regardless of how quickly they exit.

### How can we reproduce it (as minimally and precisely as possible)?

**Minimal reproducer (no Tekton required):**

```yaml
apiVersion: v1
kind: Pod
metadata:
  generateName: fast-exit-test-
spec:
  restartPolicy: Never
  initContainers:
  - name: fast-init
    image: busybox
    command: ["true"]  # exits immediately with code 0
  containers:
  - name: main
    image: busybox
    command: ["echo", "done"]
```

Run many of these concurrently:
```bash
for i in $(seq 1 100); do kubectl create -f fast-exit-pod.yaml & done
wait
kubectl get pods -o json | jq '.items[] | select(.status.initContainerStatuses[]?.state.terminated.exitCode == 255) | .metadata.name'
```

The issue is intermittent. Check CRI-O logs on affected nodes:
```bash
journalctl -u crio --no-pager | grep "Failed to update container state"
```

**Production context:** This was discovered via Tekton Pipelines, where init containers (`prepare`, `place-scripts`) perform fast filesystem operations (binary copy, symlink creation) and exit in <1ms. These init containers run on every single Tekton TaskRun, making the race condition a frequent production issue.

### Anything else we need to know?

- Related: #8980 (same root cause, closed without fix, only affected e2e tests)
- The `"Failed to update container state"` error in CRI-O logs appears to be the point where the exit code is lost
- Node conditions at time of failure show no memory/disk pressure — this is purely a timing issue
- Multiple independent reports from different environments and cloud providers
- Not environment-specific — affects AWS, bare metal, and other infrastructure
- Downstream tracking: https://github.com/tektoncd/pipeline/issues/9654

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# CRI-O 1.33.x (shipped with OpenShift 4.20.15)
# Also observed on earlier CRI-O versions
```

```console
$ kubectl version --output=json
# Kubernetes 1.33.x (OpenShift 4.20.15)
```

</details>

### OS version

<details>

```console
# Red Hat Enterprise Linux CoreOS (RHCOS)
# Shipped with OpenShift 4.20.15
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

Observed on AWS and other cloud environments. Not environment-specific — the issue is a timing race in container state tracking for fast-exiting processes.

</details>

### PR DESCRIPTION
**Pull request by bitoku**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

When a container exits very quickly, the OCI runtime may clean
up its state before CRI-O queries it. In this case, runtimeCmd("state")
fails and CRI-O falls back to reading the exit file. However, conmon
may not have written the exit file yet, causing CRI-O to immediately
default to exit code 255 with no retry.

Extract the existing exponential backoff wait for the exit file into a
shared waitForExitFile() function and use it in both code paths:
- Path A: when runtimeCmd("state") fails and the exit file is missing
- Path B: when runtimeCmd("state") reports the container as stopped

This ensures fast-exiting containers get the correct exit code from
conmon's exit file instead of a spurious 255.

#### Which issue(s) this PR fixes:

Fixes #9840 

#### Does this PR introduce a user-facing change?

```release-note
Fixed the race condition where cri-o reports exitCode 255 when the container exits fast.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved reliability by waiting for container exit markers when runtime state queries fail, and clarifying related logging.
  * Ensures exit time and exit code fallback to 255 when exit status cannot be determined after retries.

* **Tests**
  * Added tests validating successful detection from delayed exit markers and fallback-to-255 when none appear.

### CODE REVIEW

File: internal/oci/runtime_oci.go [hunk 1]
```diff
@@ -1163,6 +1163,28 @@ func updateContainerStatusFromExitFile(c *Container) error {
 	return nil
 }
 
+// waitForExitFile waits for the container's exit file to appear using
+// exponential backoff. Returns nil if the file appeared, or an error if it did
+// not appear within the timeout (~5s total: 500ms initial, 1.2 factor, 6 steps).
+func waitForExitFile(c *Container) error {
```
Comment (haircommander) [inline internal/oci/runtime_oci.go]: nit: define below called

File: internal/oci/runtime_oci.go [hunk 2]
```diff
@@ -1192,10 +1214,20 @@ func (r *runtimeOCI) UpdateContainerStatus(ctx context.Context, c *Container) er
...
 			c.state.Status = ContainerStateStopped
-			if err := updateContainerStatusFromExitFile(c); err != nil {
+
+			// The exit file may not exist yet if conmon hasn't written it.
+			// Wait for it to appear before defaulting to exit code 255.
+			// This prevents a race where fast-exiting containers
+			// get a spurious exit code 255.
+			waitErr := waitForExitFile(c)
+			if waitErr != nil {
 				log.Errorf(ctx, "Failed to update container status from exit file for %s: %v", c.ID(), err)
```
Comment (haircommander) [inline internal/oci/runtime_oci.go]: did you mean to use waitErr here?

File: internal/oci/runtime_oci_test.go [hunk 3]
```diff
@@ -232,6 +235,118 @@ var _ = t.Describe("Oci", func() {
...
+
+		defer cmdrunner.ResetPrependedCmd()
+
+		runner.EXPECT().Command(gomock.Any(), gomock.Any()).Return(
+			exec.Command("/bin/false"),
+		).AnyTimes()
+
+		// Write the exit file after a short delay, simulating conmon
+		// writing it after the first read attempt fails.
+		go func() {
```
Comment (haircommander) [inline internal/oci/runtime_oci_test.go]: why not spawn this closer to UpdateContainerStatus? we probably won't go through 800 ms before it's started but if we did that could be a false positive. unlikely, but just in case?

File: internal/oci/runtime_oci.go (hunk 2 above)
Comment (bitoku) [reply internal/oci/runtime_oci.go]: good catch!

Comment (bitoku) [reply internal/oci/runtime_oci.go]: good catch!

File: internal/oci/runtime_oci_test.go (hunk 3 above)
Comment (bitoku) [reply internal/oci/runtime_oci_test.go]: that sounds better. tbh I didn't think about that case.

**Comment by bitoku** [comment]
@cri-o/cri-o-maintainers PTAL
