### PR TITLE
Perform log directory validation early in Server#runPodSandbox

### LINKED ISSUE #3977: Perform log directory validation early in Server#runPodSandbox
**Description**

In Server#runPodSandbox, the validation of logDir is performed in the middle.
We should perform the validation early so that if there is misconfiguration, it can be detected ahead of operations which need to be rolled back (via deferred func's).

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you expected:**
Early validation of logDir being absolute.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
```

### PR DESCRIPTION
**Pull request by tedyu**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This PR performs log directory validation early in Server#runPodSandbox.

#### Which issue(s) this PR fixes:

Fixes #3977

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Change LGTM
but as the tests are upset

File: server/sandbox_run_linux.go [hunk 1]
```diff
@@ -46,6 +46,19 @@ func (s *Server) runPodSandbox(ctx context.Context, req *pb.RunPodSandboxRequest
...
+	// set log directory
+	logDir := sbox.Config().GetLogDirectory()
+	if logDir == "" {
+		logDir = filepath.Join(s.config.LogDir, sbox.ID())
+	}
+	if err := os.MkdirAll(logDir, 0700); err != nil {
+		return nil, err
+	}
+	// This should always be absolute from k8s.
+	if !filepath.IsAbs(logDir) {
```
Comment (harche) [inline server/sandbox_run_linux.go:58]: Shouldn't this validation be before `os.MkdirAll` above?

**Comment by umohnani8** [comment]
LGTM

**Comment by haircommander** [comment]
/approve
/lgtm

thanks @tedyu
