### PR TITLE
Ensure CloseIO is called after Start for exec

### LINKED ISSUE #4046: CloseIO is called before exec start
**Description**

When using `kubectl exec` with the `-i` option and don't provide any input, the RPC call sequence may be dis-order.

**Steps to reproduce the issue:**
1. kubectl exec -i POD_NAME date

**Describe the results you received:**

In log:

```
Aug 05 04:17:28 fedoradocker32-975ac0 crio[97226]: time="2020-08-05 04:17:28.186091648Z" level=error
msg="Failed to close stdin for container exec \"3ebcf38f49f5ecfc97fd16689ac54e8524ff56b6610d6da99eba736dbd02cd8f\""
error="exec does not exist fde479da83d3d15513e2446650b84187bcb007fc5de67dd1690e0b4f75b7eb54: not found" file="io/exec_io.go:78"
```
The RPC call sequence may be either of these:

- CloseIO -> Exec -> Start
- Exec -> CloseIO -> Start

`CloseIO` is called in https://github.com/cri-o/cri-o/blob/master/utils/io/exec_io.go#L69, a separated goroutine from main RPC call goroutine.

**Describe the results you expected:**

The RPC call sequence should be `Exec -> Start -> CloseIO`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
master branch
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by liubin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

For shim v2 `exec` API, the call sequences to runtime is uncertain.
It's may be `CloseIO` -> `Exec` -> `Start` or `Exec` -> `CloseIO` -> `Start`, or
`Exec` -> `Start` -> `CloseIO`. The last call sequence is the right one.

This PR will ensure the call sequence as `Exec` -> `Start` -> `CloseIO`.

#### Which issue(s) this PR fixes:

Fixes #4046 

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
nice thanks @liubin 
/ok-to-test
cc @fidencio

File: internal/oci/runtime_vm.go [hunk 1]
```diff
@@ -78,8 +78,8 @@ func newRuntimeVM(path string) RuntimeImpl {
 
 // CreateContainer creates a container.
 func (r *runtimeVM) CreateContainer(c *Container, cgroupParent string) (retErr error) {
-	logrus.Debug("runtimeVM.createContainer() start")
-	defer logrus.Debug("runtimeVM.createContainer() end")
+	logrus.Debug("runtimeVM.CreateContainer() start")
+	defer logrus.Debug("runtimeVM.CreateContainer() end")
```
Comment (fidencio) [inline internal/oci/runtime_vm.go:82]: I'd have this in a separate patch, together with all other Debug changes.

File: internal/oci/runtime_vm.go [hunk 2]
```diff
@@ -239,8 +239,8 @@ func (r *runtimeVM) startRuntimeDaemon(c *Container) error {
 
 // StartContainer starts a container.
 func (r *runtimeVM) StartContainer(c *Container) error {
-	logrus.Debug("runtimeVM.startContainer() start")
-	defer logrus.Debug("runtimeVM.startContainer() end")
+	logrus.Debug("runtimeVM.StartContainer() start")
+	defer logrus.Debug("runtimeVM.StartContainer() end")
```
Comment (fidencio) [inline internal/oci/runtime_vm.go:243]: I'd have this in a separate patch, together with all other Debug changes.

File: internal/oci/runtime_vm.go [hunk 3]
```diff
@@ -275,8 +275,8 @@ func (r *runtimeVM) StartContainer(c *Container) error {
 
 // ExecContainer prepares a streaming endpoint to execute a command in the container.
 func (r *runtimeVM) ExecContainer(c *Container, cmd []string, stdin io.Reader, stdout, stderr io.WriteCloser, tty bool, resize <-chan remotecommand.TerminalSize) error {
-	logrus.Debug("runtimeVM.execContainer() start")
-	defer logrus.Debug("runtimeVM.execContainer() end")
+	logrus.Debug("runtimeVM.ExecContainer() start")
+	defer logrus.Debug("runtimeVM.ExecContainer() end")
```
Comment (fidencio) [inline internal/oci/runtime_vm.go:279]: I'd have this in a separate patch, together with all other Debug changes.

File: internal/oci/runtime_vm.go [hunk 4]
```diff
@@ -294,8 +294,8 @@ func (r *runtimeVM) ExecContainer(c *Container, cmd []string, stdin io.Reader, s
 
 // ExecSyncContainer execs a command in a container and returns it's stdout, stderr and return code.
 func (r *runtimeVM) ExecSyncContainer(c *Container, command []string, timeout int64) (*ExecSyncResponse, error) {
-	logrus.Debug("runtimeVM.execSyncContainer() start")
-	defer logrus.Debug("runtimeVM.execSyncContainer() end")
+	logrus.Debug("runtimeVM.ExecSyncContainer() start")
+	defer logrus.Debug("runtimeVM.ExecSyncContainer() end")
```
Comment (fidencio) [inline internal/oci/runtime_vm.go:298]: I'd have this in a separate patch, together with all other Debug changes.

File: internal/oci/runtime_vm.go [hunk 5]
```diff
@@ -317,8 +317,8 @@ func (r *runtimeVM) ExecSyncContainer(c *Container, command []string, timeout in
 }
 
 func (r *runtimeVM) execContainerCommon(c *Container, cmd []string, timeout int64, stdin io.Reader, stdout, stderr io.WriteCloser, tty bool, resize <-chan remotecommand.TerminalSize) (exitCode int32, retErr error) {
-	logrus.Debug("runtimeVM.execContainer() start")
-	defer logrus.Debug("runtimeVM.execContainer() end")
+	logrus.Debug("runtimeVM.execContainerCommon() start")
+	defer logrus.Debug("runtimeVM.execContainerCommon() end")
```
Comment (fidencio) [inline internal/oci/runtime_vm.go:321]: I'd have this in a separate patch, together with all other Debug changes.

File: internal/oci/runtime_vm.go [hunk 6]
```diff
@@ -337,13 +337,22 @@ func (r *runtimeVM) execContainerCommon(c *Container, cmd []string, timeout int6
 	}
 	defer execIO.Close()
 
+	// chan to notify that can call runtime's CloseIO API
+	closeIOChan := make(chan bool)
```
Comment (fidencio) [inline internal/oci/runtime_vm.go:341]: @liubin, please. bear with me here as it may be a silly question. :-)

We're creating the channel here in order to notify who? Would containerd-shim-kata-v2 be "listening for it" and when this channel is closed, then it'd trigger the closeIO?

File: internal/oci/runtime_vm.go [hunk 7]
```diff
@@ -337,13 +337,22 @@ func (r *runtimeVM) execContainerCommon(c *Container, cmd []string, timeout int6
...
+	}()
+
 	execIO.Attach(cio.AttachOptions{
 		Stdin:     stdin,
 		Stdout:    stdout,
 		Stderr:    stderr,
 		Tty:       tty,
 		StdinOnce: true,
 		CloseStdin: func() error {
+			<-closeIOChan
```
Comment (fidencio) [inline internal/oci/runtime_vm.go:355]: Considering that's the case, this piece wouldn't trigger closeIO twice?

If so, would be okay to just close the channel and **not** call r.closeIO() here?

Comment (liubin) [reply internal/oci/runtime_vm.go:355]: As above explained, `CloseStdin` will be blocked to call the real underlay `r.closeIO()`

File: internal/oci/runtime_vm.go (hunk 6 above)
Comment (liubin) [reply internal/oci/runtime_vm.go:341]: Hi @fidencio , containerd-shim-kata-v2 don't care and can't care about it. The chan will closed after `exec` and `start` RPCs called, and the chan is not used to notify anyone to do something, it only let the code in other goroutine to continue to run, before the chan is closed( == `exec` not `start`ed), the call to underly `CloseIO` is not permitted.

**Comment by fidencio** [comment]
LGTM
/approve

I'd like to hear from @haircommander, @umohnani8, @mrunalp as well (not all of them, but some of them are enough already ;-))

**Comment by fidencio** [comment]
@liubin, btw, I noticed you completely removed the debug changes you had in your first series.
Would be possible to have then back, as a patch atop of this one? That patch was good to get in as well, just had to be split.

**Comment by haircommander** [comment]
@liubin should this still be marked as WIP?

**Comment by liubin** [comment]
> @liubin, btw, I noticed you completely removed the debug changes you had in your first series.
> Would be possible to have then back, as a patch atop of this one? That patch was good to get in as well, just had to be split.

I'm sorry that lost the commit... Added back.

**Comment by liubin** [comment]
> @liubin should this still be marked as WIP?

No, I'll remove it.

**Comment by haircommander** [comment]
/approve

LGTM
