### PR TITLE
sandbox: Make sure the label annotation is proper JSON

### LINKED ISSUE #3511: cri-o crashing on restart
**Description**

Restarting cri-o after creating a single sandbox causes cri-o to crash with a panic.

**Steps to reproduce the issue:**

1. Start cri-o
2. Create a sandbox using `crictl runp` and this config:
```
 {
      "metadata": {
          "name": "nginx-sandbox",
          "namespace": "default",
          "attempt": 1,
          "uid": "hdishd83djaidwnduwk28bcsb"
      },
      "log_directory": "/tmp",
      "linux": {
      }
  }
```
3. Restart cri-o

**Describe the results you received:**

cri-o crashes with this in the logs:

```
NFO[2020-04-02 09:33:53.984489191Z] Update default CNI network name to crio       file="ocicni/ocicni.go:375"
DEBU[2020-04-02 09:33:53.986316735Z] Golang's threads limit set to 57060           file="server/server.go:291"
WARN[2020-04-02 09:33:53.988149010Z] Could not restore sandbox 25dd18310936e5099c98d92affc41472d8a55b3a6e248382e89836d35852b38d container 25dd18310936e5099c98d92affc41472d8a55b3a6e248382e89836d35852b38d: unexpected end of JSON input  file="server/server.go:188"
WARN[2020-04-02 09:33:53.989093296Z] Unable to delete container k8s_POD_nginx-sandbox_default_hdishd83djaidwnduwk28bcsb_1: unlinkat /var/run/containers/storage/overlay-containers/25dd18310936e5099c98d92affc41472d8a55b3a6e248382e89836d35852b38d/userdata/shm: device or resource busy  file="server/server.go:191"
WARN[2020-04-02 09:33:53.989917887Z] Unable to delete container k8s_nginx-sandbox_default_hdishd83djaidwnduwk28bcsb_1: identifier is not a container  file="server/server.go:191"
WARN[2020-04-02 09:33:53.989964625Z] Deleting all containers under sandbox 25dd18310936e5099c98d92affc41472d8a55b3a6e248382e89836d35852b38d since it could not be restored  file="server/server.go:201"
DEBU[2020-04-02 09:33:53.990103525Z] Sandboxes: []                                 file="server/server.go:418"
DEBU[2020-04-02 09:33:53.991350205Z] Registered SIGHUP watcher for config          file="config/reload.go:32"
DEBU[2020-04-02 09:33:53.991553502Z] Monitoring "/usr/share/containers/oci/hooks.d" for hooks  file="hooks/monitor.go:43"
panic: attempted to update last-writer in lockfile without the write lock

goroutine 64 [running]:
github.com/containers/storage/pkg/lockfile.(*lockfile).Touch(0xc000349540, 0xc0005fc960, 0x0)
        /root/cri-o/vendor/github.com/containers/storage/pkg/lockfile/lockfile_unix.go:193 +0x235
github.com/containers/storage.(*containerStore).Touch(0xc00049e540, 0x3e, 0xc000444050)
        /root/cri-o/vendor/github.com/containers/storage/containers.go:588 +0x33
github.com/containers/storage.(*containerStore).Save(0xc00049e540, 0x0, 0x0)
        /root/cri-o/vendor/github.com/containers/storage/containers.go:228 +0x202
github.com/containers/storage.(*containerStore).Delete(0xc00049e540, 0xc00005ae00, 0x39, 0x0, 0x0)
        /root/cri-o/vendor/github.com/containers/storage/containers.go:405 +0x26c
github.com/containers/storage.(*store).DeleteContainer.func2(0xc0001013e0, 0x21c56c0, 0xc00049e540, 0xc00005ae00, 0x39, 0xc0005ef640)
        /root/cri-o/vendor/github.com/containers/storage/store.go:2335 +0x49
created by github.com/containers/storage.(*store).DeleteContainer
        /root/cri-o/vendor/github.com/containers/storage/store.go:2334 +0x540
```

**Describe the results you expected:**

cri-o successfully restarts and restores the pod sandbox

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 
Version:       1.18.0-dev
GitCommit:     7e8ccf9364af5138daf83fc22a1e1d47e42a8e90
GitTreeState:  dirty
BuildDate:     2020-04-01T13:22:18Z
GoVersion:     go1.14.1
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

but also happens with 1.16 and 1.17

cc @saschagrunert

### PR DESCRIPTION
**Pull request by rhafer**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

sandbox: Make sure the label annotation is proper JSON
    
The io.kubernetes.cri-o.Labels annotation is supposed to contain a JSON formatted string. Make sure that we set a proper JSON value (null) even if there are no labels. The empty string '' that was used before is not valid JSON.

#### Which issue(s) this PR fixes:

Fixes #3511

#### Special notes for your reviewer:

cc @saschagrunert 

#### Does this PR introduce a user-facing change?

```release-note
- Empty sandbox labels are now serialized into proper JSON (`null`)
```

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test

LGTM

**Comment by haircommander** [comment]
so weird that crun sometimes fails to buld..
/retest

File: internal/lib/container_server.go [hunk 1]
```diff
@@ -151,11 +151,11 @@ func (c *ContainerServer) LoadSandbox(id string) error {
 	}
 	var m rspec.Spec
 	if err := json.Unmarshal(config, &m); err != nil {
-		return err
+		return errors.Wrap(err, "error unmarshalling sandbox spec")
 	}
 	labels := make(map[string]string)
 	if err := json.Unmarshal([]byte(m.Annotations[annotations.Labels]), &labels); err != nil {
-		return err
+		return errors.Wrapf(err, "error unmarshalling %s annotation", annotations.Labels)
```
Comment (TomSweeneyRedHat) [inline internal/lib/container_server.go:158]: Might be good to add a further descriptor to each of these lines so that they're unique.  It will make searching for the error easier if/when it pops.
Suggest: "%s annotation" -> "%s annotation labels"
for this one, then metadata, portmappings and namespaceoptons for 2, 4, and 5 below.  I the third, annotations at line 182, is fine as is.

Comment (rhafer) [reply internal/lib/container_server.go:158]: Hm, not sure what you mean here. It already add the problematic annotation to the log message. It looks like this:

`error unmarshalling io.kubernetes.cri-o.Labels annotation`
`error unmarshalling io.kubernetes.cri-o.Metadata annotation`

 
are you suggesting something like:

`error unmarshalling io.kubernetes.cri-o.Labels annotation labels`
`error unmarshalling io.kubernetes.cri-o.Metadata annotation metadata`

Does that really add any value?

File: server/sandbox_run_linux.go [hunk 2]
```diff
@@ -185,13 +185,12 @@ func (s *Server) runPodSandbox(ctx context.Context, req *pb.RunPodSandboxRequest
...
 	// Add special container name label for the infra container
-	labelsJSON := []byte{}
 	if labels != nil {
 		labels[types.KubernetesContainerNameLabel] = leaky.PodInfraContainerName
-		labelsJSON, err = json.Marshal(labels)
-		if err != nil {
-			return nil, err
-		}
+	}
+	labelsJSON, err := json.Marshal(labels)
```
Comment (saschagrunert) [inline server/sandbox_run_linux.go:191]: I assume that marshaling `nil` converts to `{}`, right?

Comment (rhafer) [reply server/sandbox_run_linux.go:191]: Actually `nil` converts to `null`

Comment (saschagrunert) [reply server/sandbox_run_linux.go:191]: Ah okay, but wouldn't this cause to fail that line:
https://github.com/cri-o/cri-o/blob/92863e3b30774b6329ffa0790073d29b9ee9dc7b/internal/lib/container_server.go#L157

Comment (rhafer) [reply server/sandbox_run_linux.go:191]: No. It doesn't fail. `m.Annotations[annotations.Labels]` in `"null"` in that case. And that is valid JSON.

Comment (saschagrunert) [reply server/sandbox_run_linux.go:191]: Awesome, thanks for the clarification.

File: internal/lib/container_server.go (hunk 1 above)
Comment (TomSweeneyRedHat) [reply internal/lib/container_server.go:158]: My bad, I'd not picked up a description would be there.  I thought it was just going to be a the value like an id or some such.  No change needed and thanks!

**Comment by mrunalp** [comment]
Thanks for the fix! Do you mind opening cherry-pick to 1.16 and 1.17?
