### PR TITLE
Reload config should remove pinned images when an empty list is provided

### LINKED ISSUE #8202: crio v1.29.4 config reload does not update removed pinned_images
### What happened?

```
crio --version
crio version 1.29.4-6.rhaos4.16.git0e93ae2.el9
Version:        1.29.4-6.rhaos4.16.git0e93ae2.el9
```

Verify  status of unpinned image
```
crictl image --pinned quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5f93519952ee4389c0b5a380a49eb74cbb8b3b040da843f31fee5b3ba8fa8515
IMAGE                                            TAG                 IMAGE ID            SIZE                PINNED
quay.io/openshift-release-dev/ocp-v4.0-art-dev   <none>              94a4bca6c68c4       364MB               false
```

Update crio config adding image to set and reload crio
```
[crio]
  [crio.image]
    pinned_images = ["quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5f93519952ee4389c0b5a380a49eb74cbb8b3b040da843f31fee5b3ba8fa8515"]
```

Image now shown as pinned
```
crictl image --pinned quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5f93519952ee4389c0b5a380a49eb74cbb8b3b040da843f31fee5b3ba8fa8515
IMAGE                                            TAG                 IMAGE ID            SIZE                PINNED
quay.io/openshift-release-dev/ocp-v4.0-art-dev   <none>              94a4bca6c68c4       364MB               true
```
Remove image from set

```
[crio]
  [crio.image]
```
or
```
[crio]
  [crio.image]
    pinned_images = []
```
reload service and it still shows pinned

```
crictl image --pinned quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5f93519952ee4389c0b5a380a49eb74cbb8b3b040da843f31fee5b3ba8fa8515
IMAGE                                            TAG                 IMAGE ID            SIZE                PINNED
quay.io/openshift-release-dev/ocp-v4.0-art-dev   <none>              94a4bca6c68c4       364MB               true
```
```
crio status config | grep pinned_images
INFO[2024-05-20 21:09:55.934592808Z] Starting CRI-O, version: 1.29.4-6.rhaos4.16.git0e93ae2.el9, git: unknown(clean) 
    pinned_images = ["quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5f93519952ee4389c0b5a380a49eb74cbb8b3b040da843f31fee5b3ba8fa8515"]
```

### What did you expect to happen?

cache to be updated when images are removed from set

### How can we reproduce it (as minimally and precisely as possible)?

above example is reproducible with the version described

### Anything else we need to know?

original bug ref: https://github.com/cri-o/cri-o/issues/7954

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.29.4-6.rhaos4.16.git0e93ae2.el9
Version:        1.29.4-6.rhaos4.16.git0e93ae2.el9
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
GoVersion:      go1.21.9 (Red Hat 1.21.9-1.el9_4)
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  rpm_crashtraceback
  libtrust_openssl
  selinux
  seccomp
  exclude_graphdriver_devicemapper
  exclude_graphdriver_btrfs
  containers_image_ostree_stub
LDFlags:           -compressdwarf=false -B 0xd3920d959b04383b0a796489d198b4c103702925 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 '
SeccompEnabled:   true
AppArmorEnabled:  false
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="416.94.202405081407-0"
VERSION_ID="4.16"
VARIANT="CoreOS"
VARIANT_ID=coreos
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 416.94.202405081407-0"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.okd.io/latest/welcome/index.html"
BUG_REPORT_URL="https://access.redhat.com/labs/rhir/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.16"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.16"
OPENSHIFT_VERSION="4.16"
RHEL_VERSION=9.4
OSTREE_VERSION="416.94.202405081407-0"

$ uname -a
Linux ip-10-0-56-46 5.14.0-427.16.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Apr 26 18:16:09 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
AWS 4.16 nightly AWS
</details>

### PR DESCRIPTION
**Pull request by roman-kiselenko**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #8202

#### Does this PR introduce a user-facing change?

```release-note
Reload config should remove pinned images when an empty list is provided
```

### CODE REVIEW

File: pkg/config/reload.go [hunk 1]
```diff
@@ -148,6 +150,16 @@ func (c *Config) ReloadPauseImage(newConfig *Config) error {
 // ReloadPinnedImages updates the PinnedImages with the provided `newConfig`.
 // The method print log in case of any updates.
 func (c *Config) ReloadPinnedImages(newConfig *Config) {
+	if len(newConfig.PinnedImages) == 0 {
+		c.PinnedImages = newConfig.PinnedImages
+		return
+	}
```
Comment (kwilczynski) [inline pkg/config/reload.go:156]: Setting the value to an empty slice might be more explicit.

```suggestion
	if len(newConfig.PinnedImages) == 0 {
		c.PinnedImages = []string{}
		return
	}
```

File: pkg/config/reload.go [hunk 2]
```diff
@@ -148,6 +150,16 @@ func (c *Config) ReloadPauseImage(newConfig *Config) error {
...
+	sort.Strings(newConfig.PinnedImages)
+	sort.Strings(c.PinnedImages)
+
+	if cmp.Equal(newConfig.PinnedImages, c.PinnedImages) {
+		return
+	}
```
Comment (kwilczynski) [inline pkg/config/reload.go:162]: This is a nice optimisation here. Correct? This can also be streamlined as follows:

```suggestion
	if cmp.Equal(c.PinnedImages, newConfig.PinnedImages,
		cmpopts.SortSlices(func(a, b string) bool {
			return a < b
		}),
	) {
		return
	}
```

Perhaps it's a bit awkward-looking when wrapped with an if-statement.

Assume that there is "github.com/google/go-cmp/cmp/cmpopts" an import added.

Comment (kwilczynski) [reply pkg/config/reload.go:162]: That said, this `cmp.Equal()` could probably be used to retire the rest of this function body, correct? I am not sure what the rest of it aims to do, really. It also appears broken, for example:

- Initiate state of pinned_images set using configuration file

```toml
  [crio.image]
    default_transport = "docker://"
    global_auth_file = ""
    pause_image = "registry.k8s.io/pause:3.9"
    pause_image_auth_file = ""
    pause_command = "/pause"
    pinned_images = ["abc", "def"]
    signature_policy = ""
    signature_policy_dir = "/etc/crio/policies"
    image_volumes = "mkdir"
    big_files_temporary_dir = ""
    auto_reload_registries = false
```

- Updated the configuration file and send SIGHUP to reload configuration

```toml
  [crio.image]
    default_transport = "docker://"
    global_auth_file = ""
    pause_image = "registry.k8s.io/pause:3.9"
    pause_image_auth_file = ""
    pause_command = "/pause"
    pinned_images = ["", "", "xyz"]
    signature_policy = ""
    signature_policy_dir = "/etc/crio/policies"
    insecure_registries = ["127.0.0.0/8"]
    image_volumes = "mkdir"
    big_files_temporary_dir = ""
    auto_reload_registries = false
```

What? That can't be right...

There is also a matter of silently injecting pause_image, which makes sense, but should probably be handled a little bit better, for example:

- Initial state, CRI-O was just started

```toml
[crio.image]
default_transport = "docker://"
global_auth_file = ""
pause_image = "registry.k8s.io/pause:3.9"
pause_image_auth_file = ""
pause_command = "/pause"
signature_policy = ""
signature_policy_dir = "/etc/crio/policies"
image_volumes = "mkdir"
big_files_temporary_dir = ""
auto_reload_registries = false
``` 

Note: the pinned_images list is entirely missing.

- After sending SIGHUP to reload current configuration, but there were no new changes provided...

```toml
[crio.image]
default_transport = "docker://"
global_auth_file = ""
pause_image = "registry.k8s.io/pause:3.9"
pause_image_auth_file = ""
pause_command = "/pause"
pinned_images = ["registry.k8s.io/pause:3.9"]
signature_policy = ""
signature_policy_dir = "/etc/crio/policies"
insecure_registries = ["127.0.0.0/8"]
image_volumes = "mkdir"
big_files_temporary_dir = ""
auto_reload_registries = false
```

Hmm, something's afoot here...

We should fix this, I think.

Comment (roman-kiselenko) [reply pkg/config/reload.go:162]: That's a good catch 👍 

By the way, I'm thinking about [`regexForPinnedImages`](https://github.com/cri-o/cri-o/blob/main/internal/storage/image.go#L96) and the `pinned_images` list. They might be merged into one list and passed to `imageService`. 

We could build a `pinned_images` list in the `config` package and move the logic below to the right place. Hence `internal/storage/image` would work with a compiled list of `pinned_images` + `pause_image`. 

https://github.com/cri-o/cri-o/blob/747c152817970360fafa2b7264818681436c0939/internal/storage/image.go#L858-L860

@cri-o/cri-o-maintainers WDYT?

Comment (kwilczynski) [reply pkg/config/reload.go:162]: Something that @LenkaSeg might want to keep a note of, given the other work on configuration reload.

File: pkg/config/reload.go [hunk 3]
```diff
@@ -148,21 +151,29 @@ func (c *Config) ReloadPauseImage(newConfig *Config) error {
...
 // The method print log in case of any updates.
 func (c *Config) ReloadPinnedImages(newConfig *Config) {
-	updatedPinnedImages := make([]string, len(newConfig.PinnedImages))
-	updatedPinnedImageList := false
+	if len(newConfig.PinnedImages) == 0 {
+		c.PinnedImages = []string{}
+		return
+	}
+	sort.Strings(newConfig.PinnedImages)
+	sort.Strings(c.PinnedImages)
```
Comment (kwilczynski) [inline pkg/config/reload.go:159]: These are not needed as `cmp.Equal()` uses the `cmpopts.SortSlices()` callback.

File: pkg/config/reload.go [hunk 4]
```diff
@@ -148,21 +151,29 @@ func (c *Config) ReloadPauseImage(newConfig *Config) error {
...
-	for i, image := range newConfig.PinnedImages {
-		if i < len(c.PinnedImages) && image == c.PinnedImages[i] {
+	if cmp.Equal(c.PinnedImages, newConfig.PinnedImages,
+		cmpopts.SortSlices(func(a, b string) bool {
+			return a < b
+		}),
+	) {
+		return
+	}
+	newList := []string{}
```
Comment (kwilczynski) [inline pkg/config/reload.go:168]:
```suggestion

	pinnedImages := []string{}
```

File: pkg/config/reload.go [hunk 5]
```diff
@@ -148,21 +151,29 @@ func (c *Config) ReloadPauseImage(newConfig *Config) error {
...
-		updatedPinnedImages[i] = image
-		updatedPinnedImageList = true
-	}
-
-	if updatedPinnedImageList {
-		logConfig("pinned_images", strings.Join(updatedPinnedImages, ", "))
-		c.PinnedImages = updatedPinnedImages
+		newList = append(newList, img)
 	}
+	logConfig("pinned_images", strings.Join(newList, ", "))
```
Comment (kwilczynski) [inline pkg/config/reload.go:175]: We probably don't care about the space?

```suggestion
	logConfig("pinned_images", strings.Join(newList, ","))
```

**Comment by roman-kiselenko** [comment]
I guess there is a bug somewhere (in the test), `fedora-kata` tests don't [wait](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/cri-o_cri-o/8213/pull-ci-cri-o-cri-o-main-ci-fedora-kata/1797689029882286080/artifacts/fedora-kata/cri-o-gather/artifacts/testout.txt#:~:text=%23%20time%3D%222024%2D06%2D03%2019%3A11%3A57.305737380Z%22%20level%3Dinfo%20msg%3D%22Reloading%20configuration%22%20file%3D%22config/reload.go%3A21%22) 

`Configuration reload completed` log entry and returns early.

**Comment by haircommander** [comment]
cc @littlejawa

**Comment by roman-kiselenko** [comment]
@haircommander 

I think the `kata` itself does nothing here. The problem is that the test waits log message `Configuration reload completed` two times and, in both cases catches only the first entry. 

I'm going to change a test to reflect both reloads

**Comment by littlejawa** [comment]
Took a quick look at it but from what I understand, the changes and the test itself are independent of the runtime. Kata is not involved here.
If there is a difference of behavior with kata, it must be because of the environment variables and config file settings that are added for kata in the CI job itself. They can conflict with other assumptions made by the test scripts.
I've been hurt by problems like that before, so I can help troubleshoot. But the bottom line is that there's no reason for "kata" to make a difference here.

**Comment by roman-kiselenko** [comment]
It looks like I catch https://github.com/kubernetes-sigs/cri-tools/pull/1429 

I'm going to wait for a revert.

**Comment by hexfusion** [comment]
@roman-kiselenko thanks for the progress its unclear what needs to be reverted are you saying this[1] pr?

[1] https://github.com/kubernetes-sigs/cri-tools/pull/1429

**Comment by roman-kiselenko** [comment]
> @roman-kiselenko thanks for the progress its unclear what needs to be reverted are you saying this[1] pr?
> 
> [1] [kubernetes-sigs/cri-tools#1429](https://github.com/kubernetes-sigs/cri-tools/pull/1429)

I was waiting for this [PR](https://github.com/kubernetes-sigs/cri-tools/pull/1440) to be merged. 

/unhold

**Comment by roman-kiselenko** [comment]
@cri-o/cri-o-maintainers PTAL

**Comment by haircommander** [comment]
/approve

thank you!
/cherry-pick release-1.30

**Comment by roman-kiselenko** [comment]
> hmm... it looks the test is a bit flaky on `fedora-kata` https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/cri-o_cri-o/8213/pull-ci-cri-o-cri-o-main-ci-fedora-kata/1802693012262752256/artifacts/fedora-kata/cri-o-gather/artifacts/testout.txt

AFAIK it's related to Kata, should we disable it?

**Comment by littlejawa** [comment]
> > hmm... it looks the test is a bit flaky on `fedora-kata` https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/cri-o_cri-o/8213/pull-ci-cri-o-cri-o-main-ci-fedora-kata/1802693012262752256/artifacts/fedora-kata/cri-o-gather/artifacts/testout.txt
> 
> AFAIK it's related to Kata, should we disable it?

I'm still not sure about that.
This is all about crio config, and kata is not involved there.

From the logs pointed by the link above, the test is running fine with kata until the end, including reloading the config with no pinned images. The test fails when doing a "crictl images" and seeing the image is still marked as pinned.

Looking up the logic of the test, and the workflow of the code, I think there is a possible race condition:
- In the [reload go routine](https://github.com/cri-o/cri-o/blob/e34116dd2ec84de7b000832003ca86684b53577c/server/server.go#L579), we call "s.config.Reload()", then "s.storageImageServer().UpdatePinnedImagesList()"
  The first will reload the config, and generates the log messages that the test is expecting.
  The second will update the regexp that we use to mark images as pinned or not when we do ListImages or ImageStatus.

- The test is expecting the log "pinned_images = []", which is generated by "Reload()". When it finds it, the next thing it does is to call "crictl images".

I think that if somehow the call to UpdatePinnedImagesList() is not done by the time the crictl call is answered, you can get the wrong result.

As part of the reload (still according to the logs above), the runtime config is reloaded after the pinned images list. Since we're adding a runtime with kata, the timing for the reload function must be *slightly* different than without kata. I actually see that after the ListImages log (wich is the answer to your "crictl images" call), we have some logs showing that the runtime config is still being processed by the "Reload()" function.
I think this explains the error that I see in the logs, and why it is flaky.

Again, this is not kata-specific. If it is a timing condition, any non-vanilla config file could generate the same error.

Could you add a wait_for_log call in your test, and wait for the reload function's "Configuration reload completed" message before doing your "crictl" calls?
If I'm not wrong, this should synchronize everything.

**Comment by roman-kiselenko** [comment]
@littlejawa 

> Could you add a wait_for_log call in your test, and wait for the reload function's "Configuration reload completed" message before doing your "crictl" calls?

I've added `wait_for_log "Configuration reload completed"` but my assumption is a log entry 
 `"Configuration reload completed"` occurs several times and the test finds the first entry.

**Comment by littlejawa** [comment]
> @littlejawa
> 
> > Could you add a wait_for_log call in your test, and wait for the reload function's "Configuration reload completed" message before doing your "crictl" calls?
> 
> I've added `wait_for_log "Configuration reload completed"` but my assumption is a log entry `"Configuration reload completed"` occurs several times and the test finds the first entry.

Ah... you may be right :-( I'm not sure how "wait_for_log" works.
Maybe not the right fix then. But I'm pretty sure this is the root cause.

I hate saying this, but sometimes "sleep" calls helps :-p

**Review by sohankunkerkar — APPROVED** [review]
CI looks green now
/lgtm

File: pkg/config/reload.go [hunk 6]
```diff
@@ -145,24 +147,34 @@ func (c *Config) ReloadPauseImage(newConfig *Config) error {
...
-// The method print log in case of any updates.
+// ReloadPinnedImages replace the PinnedImages
+// with the provided `newConfig.PinnedImages`.
+// The method skips empty items and prints a log message.
 func (c *Config) ReloadPinnedImages(newConfig *Config) {
-	updatedPinnedImages := make([]string, len(newConfig.PinnedImages))
-	updatedPinnedImageList := false
+	if len(newConfig.PinnedImages) == 0 {
+		c.PinnedImages = []string{}
+		logConfig("pinned_images", "[]")
```
Comment (kwilczynski) [inline pkg/config/reload.go:156]: Ah nice catch. Makes sense :+1:

**Comment by kwilczynski** [comment]
@cri-o/cri-o-maintainers, we could use some overrides here. Thank you!

**Comment by littlejawa** [comment]
> @cri-o/cri-o-maintainers, we could use some overrides here. Thank you!

Following our discussion above, the test may still be flaky. The use of "wait_for_log" on the "Configuration reload completed" message may not be reliable...
Please review carefully. Any advice is welcome to make sure the test doesn't try to get image status before the config reload is complete.

**Comment by roman-kiselenko** [comment]
> > @cri-o/cri-o-maintainers, we could use some overrides here. Thank you!
> 
> Following our discussion above, the test may still be flaky. The use of "wait_for_log" on the "Configuration reload completed" message may not be reliable... Please review carefully. Any advice is welcome to make sure the test doesn't try to get image status before the config reload is complete.

I've added a `sleep 0.5` point, let's try with it. 🤞

**Comment by kwilczynski** [comment]
> > @cri-o/cri-o-maintainers, we could use some overrides here. Thank you!
> 
> Following our discussion above, the test may still be flaky.
[...]
> Please review carefully.

@littlejawa, no worries. I was under the impression that we were able to resolve issues here already.

**Comment by kwilczynski** [comment]
/hold

To resolve issues with flaky tests.

**Comment by sohankunkerkar** [comment]
I think we need to unblock this work by disabling the test on `fedora-kata` and filing a tracking issue for it.

**Comment by roman-kiselenko** [comment]
> I think we need to unblock this work by disabling the test on `fedora-kata` and filing a tracking issue for it.

SGTM @cri-o/cri-o-maintainers There is an umbrella [issue](https://github.com/cri-o/cri-o/issues/8074).

**Comment by sohankunkerkar** [comment]
> > I think we need to unblock this work by disabling the test on `fedora-kata` and filing a tracking issue for it.
> 
> SGTM @cri-o/cri-o-maintainers There is an umbrella [issue](https://github.com/cri-o/cri-o/issues/8074).

@roman-kiselenko I'm not sure how it's related to the above issue. Could you create a separate one? 
Also, you need to skip this test on `fedora-kata`.

**Comment by roman-kiselenko** [comment]
@sohankunkerkar, I've skipped the flaky test on kata. 

I will create a separate issue after the successful merge.

**Comment by kwilczynski** [comment]
@roman-kiselenko, thank you!

Let's get this merged and we can fix/investigate the other issues separately, indeed.
