### PR TITLE
Do not remove existing runtime handler

### LINKED ISSUE #3536: Unable to add drop in config for kata runtime
**Description**

if you leave the default `/etc/crio/crio.conf.d/00-default.conf` untouched and try to add a kata runtime drop in config say, `50-kata.conf` crio fails with following error,
```bash
$ cat /etc/crio/crio.conf.d/50-kata.conf
[crio.runtime.runtimes.kata-qemu]
runtime_path="/usr/bin/kata-runtime"
```
```bash
#./crio
FATA[2020-04-07 15:18:12.097027625+05:30] Validating runtime config: default_runtime set to "runc", but no runtime entry was found for it 
```

If I comment out runc related sections from /etc/crio/crio.conf.d/00-default.conf ,
```toml
#[crio.runtime.runtimes.runc]
#runtime_path = ""
#runtime_type = "oci"
#runtime_root = "/run/runc"
```
and append it to 50-kata.conf ,
```toml
[crio.runtime.runtimes.kata-qemu]
runtime_path="/usr/bin/kata-runtime"
[crio.runtime.runtimes.runc]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/runc"
```
crio comes up fine.
```bash
#./crio
WARN[2020-04-07 15:23:33.538555837+05:30] Skipping invalid hooks directory: stat /usr/share/containers/oci/hooks.d: no such file or directory 
INFO[2020-04-07 15:23:33.538625571+05:30] No seccomp profile specified, using the internal default 
INFO[2020-04-07 15:23:33.538634284+05:30] AppArmor is disabled by the system or at CRI-O build-time 
WARN[2020-04-07 15:23:33.540659588+05:30] Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
INFO[2020-04-07 15:23:33.549800080+05:30] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist 
INFO[2020-04-07 15:23:33.549827144+05:30] Update default CNI network name to podman    
WARN[2020-04-07 15:23:33.558814024+05:30] Error parsing metadata for fe5bcf80fbe5a549bbbfe9f7c291550ae895f6e625f223a7740a72ea46c17b86: unexpected end of JSON input, ignoring 
WARN[2020-04-07 15:23:33.559496090+05:30] Error parsing metadata for 85fcb82f7fe6e99ea09c841732416d29178cc7c333f2b9979233da890c92df9b: unexpected end of JSON input, ignoring 
```

**Steps to reproduce the issue:**
1. create a crio drop in file for kata runtime, 
```bash
$ cat /etc/crio/crio.conf.d/50-kata.conf 
[crio.runtime.runtimes.kata-qemu]
runtime_path="/usr/bin/kata-runtime"
```
2. restart crio

**Describe the results you received:**
```bash
#./crio
FATA[2020-04-07 15:18:12.097027625+05:30] Validating runtime config: default_runtime set to "runc", but no runtime entry was found for it 
```

**Describe the results you expected:**
crio should have started with `runc` and `kata` both runtimes enabled. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
clone from master 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by harche**
Fixes - #3536

Signed-off-by: Harshal Patil <harpatil@redhat.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR addresses the concerns raised in #3536 about having runtimes other than default `runc` be responsible for making sure the existing `runc` configuration is not broken. For example, please refer to #3536 for additional info on how it affects the users of Kata runtime. 

#### Which issue(s) this PR fixes:

Fixes #3536 

#### Does this PR introduce a user-facing change?
Yes

```release-note
Adding additional runtime handler doesn't require the user to copy existing default runtime handler configuration. The existing default runtime handler configuration will be preserved while adding the new runtime handler. 
```

### CODE REVIEW

File: pkg/config/config.go [hunk 1]
```diff
@@ -439,20 +439,11 @@ func (c *Config) UpdateFromFile(path string) error {
...
 	}
 
-	// If the default runtime `runc` provided via DefaultConfig() is not part
-	// of the configuration file, then we have to manually remove it because
-	// the user explicitly removed it
-	runtimesKey := []string{"crio", "runtime", "runtimes"}
-	if metadata.IsDefined(runtimesKey...) &&
-		!metadata.IsDefined(append(runtimesKey, defaultRuntime)...) {
-		delete(c.Runtimes, defaultRuntime)
-	}
```
Comment (saschagrunert) [inline pkg/config/config.go:454]: I have the feeling that we move back and forth with this change. What about an alternative solution for https://github.com/cri-o/cri-o/issues/3360 (which would not work any more if we remove those lines)?

Comment (harche) [reply pkg/config/config.go:454]: @saschagrunert with this fix I tested following scenario.

Now just like in case of https://github.com/cri-o/cri-o/issues/3360, user wants to add `crun` as their runtime of choice plus they also want to use it as their `default` runtime. With this change, they don't have to change anything in the crio.conf that ships with crio. All they have to do is add following drop in config at `/etc/crio/crio.conf.d/10-crun.conf`,

```bash
[crio.runtime]
  default_runtime = "crun"
  [crio.runtime.runtimes]
    [crio.runtime.runtimes.crun]
      runtime_path="/usr/local/bin/crun"
```
When you start crio, you will see following entries with `./crio config` command,

```toml
[crio.runtime.runtimes.crun]
runtime_path = "/usr/local/bin/crun"
runtime_type = ""
runtime_root = ""

[crio.runtime.runtimes.runc]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/runc"
```
and, 
```toml
# default_runtime is the _name_ of the OCI runtime to be used as the default.
# The name is matched against the runtimes map below.
default_runtime = "crun"
```
The crio come up fine btw. 

The original intend of drop in config is to minimize the user interaction with the main crio.conf file. Having an independent drop in config allows user to focus only on the config they are interested in and not accidentally make unintentional changes to main crio.conf

In fact this PR helps the original reporter of https://github.com/cri-o/cri-o/issues/3360. Now if anyone wants to add a runtime and set it to default, all they have to do is just add a drop in config for that runtime and they are set.    

@saschagrunert @haircommander @mrunalp Let me know if I am making any sense.

Comment (saschagrunert) [reply pkg/config/config.go:454]: That's all fine from my side. The thing left open for me is how to start CRI-O if runc is not available on the host system?

Comment (harche) [reply pkg/config/config.go:454]: CRIO is explicitly adding a [default runtime](https://github.com/cri-o/cri-o/blob/master/pkg/config/config.go#L35) as `runc`. As long as we have that dependency user is not in position to remove `runc`. 

However, if you change those constants to point to `crun` and recompile,

```go
	defaultRuntime        = "crun"
	DefaultRuntimeType    = "oci"
	DefaultRuntimeRoot    = "/run/crun"
```
crio come up fine even if you remove `runc`. But now user cannot remove `crun` and add `runc` configuration. 

I think of it as an explicit declaration of dependency, user doesn't get to remove it.

**Comment by cynepco3hahue** [comment]
Our team also needs to introduce custom runtime to configure additional things on the node and start the runc after it, and we also should copy-paste the default runc runtime from the `crio.conf` file, that can bring some bugs, when the path to the default runc will be changed.
```
# cat 99-runtimes.conf 
# We should copy paste the default runtime because this snippet will override the whole runtimes section
[crio.runtime.runtimes.runc]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/runc"

[crio.runtime.runtimes.cpu-load-balance]
runtime_path = "/usr/local/bin"
```
+1 to merge this PR.

**Comment by haircommander** [comment]
rebasing off of latest master should fix the tests @harche , then we can get this in

**Comment by harche** [comment]
Thanks @haircommander

**Comment by haircommander** [comment]
I lied, you'll need https://github.com/cri-o/cri-o/pull/3911 too

**Comment by harche** [comment]
@haircommander  no problem

**Comment by haircommander** [comment]
@harche can you rebase this?

**Comment by harche** [comment]
> @harche can you rebase this?

Done. Thanks.

**Comment by AkihiroSuda** [comment]
This caused a regression: https://github.com/cri-o/cri-o/issues/4069

CRI-O can no longer start when a `runc` binary isn't present in `$PATH`
