### PR TITLE
Fix container cgroup under cgroupfs

### LINKED ISSUE #4075: cgroupfs: container created with bad cgroup path
**Description**

cri-o messes up cgroup paths for ~~cgroupv2 +~~ cgroupfs setup. **Update:** The bug is valid for both cgroupv1 and v2.

**Steps to reproduce the issue:**

~~On a cgroupv2 host (e.g. Fedora 32), ~~ in cri-o top source directory, run the following:

```console
export CONTAINER_CGROUP_MANAGER=cgroupfs
export CONTAINER_CONMON_CGROUP=pod

# fix json files so they don't contain `.slice`
./scripts/circle-setup-cgroup_manager 

# create a simple test
cd test
cat << EOF > 1.bats
load helpers

function setup() {
    setup_test
}

function teardown() {
    cleanup_test
}

@test "eh" {
    start_crio
    id=$(crictl run "$TESTDATA"/container_redis.json "$TESTDATA"/sandbox_config.json)

    crictl inspect "$id" | grep cgroupsPath 1>&2
    find /sys/fs/cgroup -name \*$id\* -type d 1>&2
    stats=$(crictl stats -o json $id)
}
EOF

# run it (as root)
JOBS=1 ./test_runner.sh 1.bats
```

**Describe the results you received:**

Excerpts from the output of the above test case.

1. Result of `crictl inspect "$id" | grep cgroupsPath`:
>          "cgroupsPath": "pod_123-456/crio-b9e3a62d9ae9edc3f97e9167bdfdb6dd73960422cf343cc6188501b05d3f88c5",

2. Result of ` find /sys/fs/cgroup -name \*$id\* -type d`:

> /sys/fs/cgroup/pids/pod_123-456/crio-conmon-b9e3a62d9ae9edc3f97e9167bdfdb6dd73960422cf343cc6188501b05d3f88c5
> /sys/fs/cgroup/pod_123-456/crio-conmon-b9e3a62d9ae9edc3f97e9167bdfdb6dd73960422cf343cc6188501b05d3f88c5
> /sys/fs/cgroup/pod_123-456/crio-conmon-b9e3a62d9ae9edc3f97e9167bdfdb6dd73960422cf343cc6188501b05d3f88c5/pod_123-456/crio-b9e3a62d9ae9edc3f97e9167bdfdb6dd73960422cf343cc6188501b05d3f88c5

3. A warning from `cricrl stats`:

> time="2020-08-12 12:39:02.476864773-07:00" level=warning msg="Unable to get stats for container bfd5732672995e847102e4970f6ceddb23d9d48e1d81ee50a785f92cbe900d70: unable to obtain cgroup stats: open /sys/fs/cgroup/pod_123-456/crio-bfd5732672995e847102e4970f6ceddb23d9d48e1d81ee50a785f92cbe900d70/memory.current: open /sys/fs/cgroup/pod_123-456/crio-bfd5732672995e847102e4970f6ceddb23d9d48e1d81ee50a785f92cbe900d70/memory.current: no such file or directory" file="server/container_stats_list.go:40" id=d469ad95-1243-4b7c-b506-6d423e898573 name=/runtime.v1alpha2.RuntimeService/ListContainerStats

**Describe the results you expected:**

Output from find (item 2 above) should show the same path as inspect's cgroupPath (item 1 above).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```console
[root@kir-rhat test]# ../bin/crio --version
crio version 1.19.0-dev
Version:       1.19.0-dev
GitCommit:     e2151c78e148001f7e1a8558b11d17c276c2032d
GitTreeState:  dirty
BuildDate:     2020-08-12T18:16:55Z
GoVersion:     go1.14.6
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 32

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

In case cgroupfs cgroup manager is used, the container got created under
the conmon cgroup (rather than under the root), and then the stats
doesn't work because the cgroup path is invalid.

For example, if the conmon cgroup is created as
/sys/fs/cgroup/pod_123-456/crio-conmon-<ID>, then the container cgroup
is created as
/sys/fs/cgroup/pod_123-456/crio-conmon-<ID>/pod_123-456/crio-<ID>,
rather than sys/fs/cgroup/pod_123-456/crio-conmon-<ID>.

The `cricrl stats` then fails as it can't find the container cgroup.

This happens because the cgroupsPath set in spec for such containers
is not absolute, so the cgroup is created under the current cgroup,
which is that of conmon.

The fix is easy.

#### Which issue(s) this PR fixes:

Fixes #4075 

#### Special notes for your reviewer:

Found while working on https://github.com/cri-o/cri-o/pull/4064. That PR has a test case (in test/stats.bats) which will check this issue, so there's no test case in here.

#### Does this PR introduce a user-facing change?

```release-note
Fix the container cgroup in case cgroupfs cgroup manager is used (#4075)
```

### CODE REVIEW

File: internal/config/cgmgr/cgroupfs.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ func (*CgroupfsManager) ContainerCgroupPath(sbParent, containerID string) string
 	if sbParent != "" {
 		parent = sbParent
 	}
-	return filepath.Join(parent, crioPrefix+"-"+containerID)
+	return filepath.Join("/", parent, crioPrefix+"-"+containerID)
```
Comment (TomSweeneyRedHat) [inline internal/config/cgmgr/cgroupfs.go:41]: IDK, but should we be doing a securejoin here?

Comment (kolyshkin) [reply internal/config/cgmgr/cgroupfs.go:41]: I don't think so.

1. This is not an absolute path, but a one relative to /sys/fs/cgroup.
2. runc/crun [should] do sanity checks.
3. The only untrusted component here is parent, this is a cgroup of sandbox, which is also created by cri-o.

**Comment by kolyshkin** [comment]
CI is all green now, although `tide` status was not updated here.
