### PR TITLE
server/*: Fix a bug where the GID is not added to /etc/group when run_as_group is set

### LINKED ISSUE #8216: Containers runs as a member of group should have its gid in /etc/group inside container
### What happened?

1. Create POD with below securitycontext  
securityContext:
    runAsUser: 64892
    runAsGroup: 6263
    fsGroup: 123

2. Inside container no group id is created at /etc/group
bash-5.2$ id
uid=64892(64892) gid=6263 groups=6263,123
bash-5.2$ id 64892
uid=64892(64892) gid=0(root) groups=0(root)
bash-5.2$ cat /etc/passwd | grep 64892
64892:x:64892:0:64892 user:/:/sbin/nologin
bash-5.2$ cat /etc/group | grep 6263
bash-5.2$

3.it leads to sysrepo starts failure inside container as it checks if group id exists at /etc/group 
https://github.com/sysrepo/sysrepo

### What did you expect to happen?

if group id is appointed by runAsGroup, this group id should exist at /etc/group inside container.
just like uid case in below ticket
https://github.com/cri-o/cri-o/pull/2022

### How can we reproduce it (as minimally and precisely as possible)?

set runAsGroup explicitly and check if group id exists in /etc/group inside container.

### Anything else we need to know?

_No response_

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.27.4-7.2.rhaos4.14.git082c52f.el9
Version:        1.27.4-7.2.rhaos4.14.git082c52f.el9
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
GoVersion:      go1.20.12
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:
  rpm_crashtraceback
  libtrust_openssl
  selinux
  seccomp
  exclude_graphdriver_devicemapper
  exclude_graphdriver_btrfs
  containers_image_ostree_stub
LDFlags:           -compressdwarf=false -B 0x65f4e71070d8476fd679ce6e0b5a627a1d7db545 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 '
SeccompEnabled:   true
AppArmorEnabled:  false

$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.4",
    "gitCommit": "f7b14a92857ad1f28be2e2eaec3ae8229d4c2761",
    "gitTreeState": "clean",
    "buildDate": "2024-04-15T20:46:22Z",
    "goVersion": "go1.20.12 X:strictfipsruntime",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.1",
  "serverVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.12+7bee54d",
    "gitCommit": "656b6ddbf993fdc14b6e8cfeeb7e7eebc6c9a072",
    "gitTreeState": "clean",
    "buildDate": "2024-04-16T11:59:57Z",
    "goVersion": "go1.20.12 X:strictfipsruntime",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}



### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="414.92.202404162000-0"
VERSION_ID="4.14"
VARIANT="CoreOS"
VARIANT_ID=coreos
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 414.92.202404162000-0 (Plow)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.14/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.14"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.14"
OPENSHIFT_VERSION="4.14"
RHEL_VERSION="9.2"
OSTREE_VERSION="414.92.202404162000-0"
$ uname -a
Linux master0.hztt-vrf2-10-69-54-66.ocp.hz.nsn-rdnet.net 5.14.0-284.62.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Apr 5 09:44:49 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux


</details>


### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>
run at physical server
it's openshift from Redhat
oc version
Client Version: 4.14.0-202404151639.p0.gf7b14a9.assembly.stream-f7b14a9
Kustomize Version: v5.0.1
Server Version: 4.14.22
Kubernetes Version: v1.27.12+7bee54d

### PR DESCRIPTION
**Pull request by PannagaRao**
When securityContext of runAsGroup is added the
gid has to be added in /etc/group. Test case for
the same is also being added

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR has changes to add gid [value of RunAsGroup in SecurityContext] under /etc/group

#### Which issue(s) this PR fixes:

Fixes #8216

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug where the GID is not added to /etc/group when run_as_group is set
```

### CODE REVIEW

File: server/container_create.go [hunk 1]
```diff
@@ -229,13 +229,17 @@ func setupContainerUser(ctx context.Context, specgen *generate.Generator, rootfs
 	}
 
 	genPasswd := true
+	genGroup := true
 	for _, mount := range specgen.Config.Mounts {
 		if mount.Destination == "/etc" ||
 			mount.Destination == "/etc/" ||
```
Comment (haircommander) [inline server/container_create.go:235]: mount.Destination == "/etc" would be a reason to set genGroup to false as well.
I suggest a switch statement:
```
switch mount.Destination {
case "/etc/":
genPasswd, genGroup = false
case "/etc/passwd":
genPasswd = false
case "/etc/group"
genCgroup = false
}
```
you may need a separate function though as break statements won't work in a switch (to break out of the loop). also: don't break out of the loop on only the /etc/passwd case, as a user may have mounted /etc/passwd and /etc/group but this code as-is would only catch the former.

File: server/container_create.go [hunk 2]
```diff
@@ -229,13 +229,17 @@ func setupContainerUser(ctx context.Context, specgen *generate.Generator, rootfs
 	}
```
Comment (haircommander) [inline server/container_create.go:229]: I would expect https://github.com/cri-o/cri-o/pull/8251/files#diff-1ec6bb9cf833fd4ded46ce1feb6440f1d7532294e0445623f2f2e0bb2726ea63R226 to take the RunAsGroup field into account and then we could just rely on gid from this point on

File: server/container_create.go [hunk 3]
```diff
@@ -258,6 +262,25 @@ func setupContainerUser(ctx context.Context, specgen *generate.Generator, rootfs
 		}
 	}
 
+	if genGroup && sc.RunAsGroup != nil {
```
Comment (haircommander) [inline server/container_create.go:265]: I think we should use gid here, assuming that we can take RunAsGroup into account for gid https://github.com/cri-o/cri-o/pull/8251/files#r1625011421

File: test/pod.bats [hunk 4]
```diff
@@ -390,3 +390,33 @@ function teardown() {
 	output=$(crictl exec --sync "$ctr_id" ls -ld /etc)
 	[[ "$output" == *"test test"* ]]
 }
+
+@test "verify RunAsGroup in container" {
+  start_crio
+
+  jq '
+    .linux.security_context.run_as_user = { value: 1000 }
+    | .linux.security_context.run_as_group = { value: 1001 }
```
Comment (haircommander) [inline test/pod.bats:399]: doing this in the sandbox won't really change anything (the pause container may get it, but it won't do anything with it). I thinhk you can just use sandbox_config.json here

File: utils/utils.go [hunk 5]
```diff
@@ -231,6 +231,88 @@ func GeneratePasswd(username string, uid, gid uint32, homedir, rootfs, rundir st
 	return passwdFile, nil
 }
 
+// GenerateGroup generates a container specific group file,
+// iff gid is not defined in the containers /etc/group
+func GenerateGroup(gid uint32, rootfs, rundir string) (string, error) {
```
Comment (haircommander) [inline utils/utils.go:236]: can you refactor the shared bits between these 4 functions (Generate* and Get*)?

File: server/container_create.go (hunk 1 above)
Comment (PannagaRao) [reply server/container_create.go:235]: Will implement the suggestion

File: server/container_create.go (hunk 3 above)
Comment (PannagaRao) [reply server/container_create.go:265]: Will make this change by setting gid to pick sc.RunAsGroup value (when not null)

File: server/container_create.go (hunk 1 above)
Comment (kwilczynski) [reply server/container_create.go:235]: For the sake of completeness, the switch statement would be:

```go
	switch mount.Destination {
	case "/etc", "/etc/":
		genPasswd, genGroup = false, false
	case "/etc/passwd":
		genPasswd = false
	case "/etc/group":
		genGroup = false
	}
```

File: test/pod.bats (hunk 4 above)
Comment (PannagaRao) [reply test/pod.bats:399]: Using different RunAsGroup values at pod and container level to highlight that container specific one gets picked.

File: utils/utils.go [hunk 6]
```diff
@@ -179,56 +179,146 @@ func GetUserInfo(rootfs, userName string) (uid, gid uint32, additionalGids []uin
...
+	}
+
+	groupContent := fmt.Sprintf("%s%d:x:%d:\n", string(origContent), gid, gid)
+	groupFile := filepath.Join(rundir, "group")
+
+	return createAndSecureFile(groupFile, groupContent, os.FileMode(stat.Mode), int(stat.Uid), int(stat.Gid))
+}
+
+// checkFilePermissions checks file permissions to decide whether to skip file modification.
+func checkFilePermissions(stat unix.Stat_t, id, statId uint32) bool {
```
Comment (haircommander) [inline utils/utils.go:241]: nit: can these functions be ordered in the order they're called from the calling functions?

File: utils/utils.go [hunk 7]
```diff
@@ -179,56 +179,146 @@ func GetUserInfo(rootfs, userName string) (uid, gid uint32, additionalGids []uin
...
+		return "", fmt.Errorf("failed to chown file: %w", err)
 	}
+	return filepath, nil
+}
 
-	orig, err := os.ReadFile(originPasswdFile)
+// GetGroup takes a containermount path and group name or ID and returns
+// a matching Group structure from /etc/group.  If it cannot locate a group
+// with the provided information, an ErrNoGroupEntries is returned.
+func GetGroup(containerMount, groupIDorName string) (*user.Group, error) {
```
[the remark this answers is not in the document]
Comment (PannagaRao) [reply utils/utils.go:295]: Done

File: server/container_create.go [hunk 8]
```diff
@@ -229,11 +229,19 @@ func setupContainerUser(ctx context.Context, specgen *generate.Generator, rootfs
...
 			genPasswd = false
+			genGroup = false
+		case "/etc/passwd":
+			genPasswd = false
+		case "/etc/group":
+			genGroup = false
+		}
+
+		if !genPasswd && !genGroup {
 			break
```
Comment (haircommander) [inline server/container_create.go:245]: are we sure the "break" here breaks us out of the loop and not the switch statement? we may need a goto (even though I don't like how they look)

**Comment by haircommander** [comment]
I think pulling latest and rebasing this PR should fix the test failures

It LGTM besides one remaining question (it wouldn't hurt to have it as-is)
/approve

**Comment by haircommander** [comment]
@cri-o/cri-o-maintainers PTAL

**Review by sohankunkerkar — APPROVED** [review]
/lgtm

**Comment by kwilczynski** [comment]
/hold

Please update both the commit subject and the title of this Pull Request such that it explains what is being added.

We already know that there are "changes" made here, since this is a Pull Request.

File: utils/utils.go [hunk 9]
```diff
@@ -179,56 +179,146 @@ func GetUserInfo(rootfs, userName string) (uid, gid uint32, additionalGids []uin
...
+	origContent, err := readFileContent(passwdFilePath)
+	if err != nil || origContent == nil {
+		return "", err
+	}
+
+	if username == "" {
+		username = "default"
+	}
+	if homedir == "" {
+		homedir = "/tmp"
```
Comment (kwilczynski) [inline utils/utils.go:204]: Maybe it would be better to set this to `/nonexistent`?

@cri-o/cri-o-maintainers, thoughts?

**Comment by kwilczynski** [comment]
OK. Will cherry-pick manually.
