### PR TITLE
[1.24] Fix cgroup leak for systemd cgroup driver

### LINKED ISSUE #6349: 1.24.3 leaks pidns with cgroup v2
### What happened?

Observed that on a node where many cronjobs get scheduled (i.e.many pods being created than stopped), syslog entries appear:
```
Nov 07 08:22:18 k8s-node16 kubelet[699]: W1107 08:22:18.605965     699 container.go:589] Failed to update stats for container "/pids/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podeb779fdd_e230_4fb0_b027_f9f91f117b46.slice/crio-f1800404321299f38a4ba5dfedf95df94b825507597527b48bf3a6d9f2f3eb13.scope": unable to determine device info for dir: /var/lib/containers/storage/overlay/304bfd8df6d35aaf9a5632b9bcdc69bdd54aa9277baf2c18c4930072d017514c/diff: stat failed on /var/lib/containers/storage/overlay/304bfd8df6d35aaf9a5632b9bcdc69bdd54aa9277baf2c18c4930072d017514c/diff with error: no such file or directory, continuing to push stats
```

That is because entries under `/sys/fs/cgroup/pids/kubepods.slice/kubepods-burstable.slice/` are not cleaned up. I suspect the count of `crictl pods` and entries under the mentioned dir should be in sync, but I may be wrong.

```
# crictl pods
POD ID              CREATED             STATE               NAME                     NAMESPACE           ATTEMPT             RUNTIME
6b309d1ef5223       13 minutes ago      Ready               kube-router-dr2vh        kube-system         0                   (default)
41b1338d583b2       13 minutes ago      Ready               truenas-csi-node-5lkh5   truenas-csi         0                   (default)
b12fd8fb24ccb       13 minutes ago      Ready               promtail-vfflj           monitoring          0                   (default)
950e109f187a0       13 minutes ago      Ready               node-exporter-km99c      kube-system         0                   (default)
# ls -la /sys/fs/cgroup/pids/kubepods.slice/kubepods-burstable.slice/
total 0
drwxr-xr-x 11 root root 0 Nov  7 08:13 .
drwxr-xr-x  3 root root 0 Nov  7 08:13 ..
-r--r--r--  1 root root 0 Nov  7 08:13 cgroup.controllers
-r--r--r--  1 root root 0 Nov  7 08:13 cgroup.events
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.freeze
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.max.depth
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.max.descendants
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.procs
-r--r--r--  1 root root 0 Nov  7 08:13 cgroup.stat
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.subtree_control
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.threads
-rw-r--r--  1 root root 0 Nov  7 08:13 cgroup.type
-rw-r--r--  1 root root 0 Nov  7 08:13 cpu.pressure
-r--r--r--  1 root root 0 Nov  7 08:13 cpu.stat
-rw-r--r--  1 root root 0 Nov  7 08:13 io.pressure
drwxr-xr-x  3 root root 0 Nov  7 08:34 kubepods-burstable-pod321a0667_9839_4537_8dfe_8a2f42ed2a01.slice
drwxr-xr-x  3 root root 0 Nov  7 08:13 kubepods-burstable-pod571e43da_a130_438b_86d8_5b5fea8c2180.slice
drwxr-xr-x  3 root root 0 Nov  7 08:13 kubepods-burstable-pod57769bbc_9867_42a7_83bd_7a65fc4791ab.slice
drwxr-xr-x  3 root root 0 Nov  7 08:29 kubepods-burstable-pod5872eef3_b96b_488c_8338_265e32a9b87c.slice
drwxr-xr-x  3 root root 0 Nov  7 08:16 kubepods-burstable-podb2f5e0d7_a53b_4a33_a4ab_ca4ac994e365.slice
drwxr-xr-x  3 root root 0 Nov  7 08:13 kubepods-burstable-podb3174e7f_0cb1_47d5_8b6e_5c1b9904f07e.slice
drwxr-xr-x  3 root root 0 Nov  7 08:34 kubepods-burstable-podb3e4520f_03ad_46e0_bfcc_c1dc739260e8.slice
drwxr-xr-x  3 root root 0 Nov  7 08:16 kubepods-burstable-podeb779fdd_e230_4fb0_b027_f9f91f117b46.slice
drwxr-xr-x  3 root root 0 Nov  7 08:13 kubepods-burstable-podec55611f_6ee5_481f_9e8b_f6ae883baf29.slice
-rw-r--r--  1 root root 0 Nov  7 08:13 memory.pressure
```

Howewer I have 4 running pods, and 9 entries under /sys. kubelet/cadvisor then logs warning messages for pid namespaces not cleaned up, and this floods my logs.

### What did you expect to happen?

Expected every resource cleaned up after pod termination, logs being not flooded.

### How can we reproduce it (as minimally and precisely as possible)?

Have cgroups v2 with crio-1.24. Start and stop a pod on the node, and observe entries not being removed from `/sys/fs/cgroup/pids/kubepods.slice/kubepods-burstable.slice`.

### Anything else we need to know?

It is to be noted that with v1.25 `/sys/fs/cgroup/pids` just does not exist.

### CRI-O and Kubernetes version

<details>

```console
# crio --version
crio version 1.24.3
Version:          1.24.3
GitCommit:        251db4e7a44dd5b76586bd2f8d818691ed8413f7
GitTreeState:     clean
BuildDate:        2022-11-07T06:13:20Z
GoVersion:        go1.18.8
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        apparmor, exclude_graphdriver_devicemapper, containers_image_openpgp, containers_image_ostree_stub, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  true
```

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}
```
</details>

### OS version

<details>

```console
# On Linux:
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
# uname -a
Linux k8s-node16 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Bare metal
</details>

### PR DESCRIPTION
**Pull request by n4j**
Initial commit to get feedback from the maintainers, need to add integration tests

Closes #6349

Signed-off-by: Neeraj Shah <neerajx86@gmail.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This PR fixes an issue whereby cgroups are not cleaned up after a Pod is terminated, this is an issue with cri-o versions prior to `1.26`

#### Which issue(s) this PR fixes:
Fixes #6349 

#### Special notes for your reviewer:
This is a draft PR, I need to add integration tests for my changes.

#### Does this PR introduce a user-facing change?
No

```release-note

```

### CODE REVIEW

**Comment by n4j** [comment]
@haircommander

**Comment by n4j** [comment]
This [commit](https://github.com/cri-o/cri-o/commit/ee5d9725489c23270b070f9f9e8ff7b5a7f98978) segregated cgroup creation for systemd and non-systemd environments.

I believe call to `cgroups.NewSystemd` [creates](https://github.com/containers/common/blob/main/pkg/cgroups/cgroups_linux.go#L317) the struct but doesn't make a call to systemd via dbus to create cgroups.

Hence, when systemd is cgroup driver actual cgroup doesn't get created by cri-o but rather by systemd IMHO and when Pod terminates the cgroup gets deleted.

Idiomatically, no cgroup creation action is taken for systemd from cri-o, hence I have skipped the call to `cgroup.NewSystemd` which I believe is redundant (feel free to correct me)

In versions prior to `release-1.26` cgroup path is created for all cases via call to `cgroups.New`, since this path is of format `kubepods-besteffort-pod${K8S_POD_UID}.slice/crio-${CRIO_POD_SANDBOX_ID}.scope` rather than expected format `kubepods-besteffort-pod${K8S_POD_UID}.slice/crio-${CRIO_CONTAINER_ID}.scope` the path never gets deleted

File: internal/config/cgmgr/cgmgr.go [hunk 1]
```diff
@@ -144,6 +144,12 @@ func VerifyMemoryIsEnough(memoryLimit int64) error {
 // createSandboxCgroup takes the sandbox parent, and sandbox ID.
 // It creates a new cgroup for that sandbox, which is useful when spoofing an infra container.
 func createSandboxCgroup(sbParent, containerID string, mgr CgroupManager) error {
+	// If we are running systemd as cgroup driver then we would rely on
+	// systemd to create cgroup for us
+	if mgr.IsSystemd() {
+		return nil
+	}
+
```
Comment (haircommander) [inline internal/config/cgmgr/cgmgr.go:152]: what would you think about returning in `systemd.go:CreateSandboxCgroup` and dropping this check? we already have a spot where we know the systemd cgroup driver is being used. We could even compress this function into the cgroupfs function as well.

**Comment by haircommander** [comment]
/ok-to-test

generally, the approach LGTM. I have a code structure nit. Also, generally we start PRs from `main` and backport them. Since main is currently needlessly creating the struct, maybe we revert that and add this to main first, and backport all the way back. WDYT

**Comment by haircommander** [comment]
cc @kolyshkin

File: internal/config/cgmgr/cgmgr.go (hunk 1 above)
Comment (n4j) [reply internal/config/cgmgr/cgmgr.go:152]: @haircommander Makes sense.

About, raising PR to master and back merging to prior releases - upto version `1.25` we use `containers/podman/cgroups.go:New(path string, resources *spec.LinuxResources)` for creating `cgroupfs` cgroups, while from `1.26` we use `containers/common:cgroups_linux.go:New(path string, resources *configs.Resources)` so I'll have to raise two separate PRs IMHO.

Comment (haircommander) [reply internal/config/cgmgr/cgmgr.go:152]: yeah you may have to open multiple, but I think it will make the branches more consistent. If you'd rather not have the paperwork, one of the maintainers can do it, though we'd certainly appreciate your doing it if you feel like it!

**Comment by haircommander** [comment]
/approve 

LGTM

/retitle [1.24] Fix cgroup leak for systemd cgroup driver

**Comment by n4j** [comment]
@haircommander Do I need to take any action here to get the code merged? 

e.g. take care about failing integration test cases (I have noticed `integration / test-cgroupfs (pull_request)` failing for PR from other folks too)?

**Comment by haircommander** [comment]
```
# time="2023-02-13T16:47:43Z" level=fatal msg="run pod sandbox: rpc error: code = Unknown desc = open pod_123-456/crio-conmon-13d23e98c7dcd313911a3251fedd06ef7ee08cd7f827f9c96cb6fb0b8420fcec/cgroup.controllers: no such file or directory"
```
interesting, I've not seen this one yet, but it's not clear how this would cause it

**Comment by n4j** [comment]
@haircommander I could be wrong here but I believe `test-cgroupfs`  is failing at test `254 test workload gets configured to defaults` ([link to line](https://github.com/cri-o/cri-o/actions/runs/4165447327/jobs/7228235479#step:9:391)).

Anything I can do here to fix this?

**Comment by haircommander** [comment]
Are you able to debug the test to see if you can figure out what's going on?

**Comment by n4j** [comment]
> Are you able to debug the test to see if you can figure out what's going on?

@haircommander I can try this, but I have a hunch that `crictl rm`

**Comment by n4j** [comment]
@haircommander I executed some of the tests failing in sute `test_cgroupfs` on `release-1.24` branch on my machine and I am able to replicate test case failures.


For e.g. when I ran test cases

```bash
sudo \
 CONTAINER_CGROUP_MANAGER=cgroupfs \
 CONTAINER_CONMON_CGROUP=pod \
 bats test/infra_ctr_cpuset.bats 
```

It failed with below error

```
sudo CONTAINER_CGROUP_MANAGER=cgroupfs CONTAINER_CONMON_CGROUP=pod bats test/infra_ctr_cpuset.bats 
infra_ctr_cpuset.bats
 ✗ test infra ctr cpuset
   (in test file test/infra_ctr_cpuset.bats, line 16)
     `pod_id=$(crictl runp "$TESTDATA"/sandbox_config.json)' failed
```

This is the exact error show above is also thrown [here](https://github.com/cri-o/cri-o/actions/runs/4165447327/jobs/7228235479#step:9:162)

IMHO, this looks like a regression in `release-1.24` to me. Thoughts?

**Comment by n4j** [comment]
@haircommander Do we know when this and other backmerge PRs will be merged?

**Comment by n4j** [comment]
@haircommander Can you merge this one as well?
