### PR TITLE
Fix HostPort manager when one backend is unavailable

### LINKED ISSUE #9220: SIGSEGV when deleting pod with host port
### What happened?

When deleting a pod with a host port, crio 1.33 will SIGSEGV. It'll get in to a loop where systemd brings it back to life, attempts to terminate the pod and crashes again.

dnf list --installed | grep table
iptables-libs.x86_64                 1.8.11-8.fc42              updates
iptables-nft.x86_64                  1.8.11-8.fc42              updates
nftables.x86_64                      1:1.1.1-3.fc42             fedora
python3-nftables.x86_64              1:1.1.1-3.fc42             fedora

Judging by the stack trace, I assume the host port manager maybe trying to use iptables to do its cleanup, although its not installed. Disabling it via `--disable-hostport-mapping` fixes the crashes.
Since I also use Cilium replacing kube-proxy, this is probably ideal anyway.

iptable related warning logs
<details>

```console
May 24 15:48:30 node01 crio[217790]: time="2025-05-24T15:48:30.790504385+02:00" level=info msg="No iptables support for IPv6: iptables not available"
May 24 15:48:30 node01 crio[217790]: time="2025-05-24T15:48:30.758074182+02:00" level=warning msg="Couldn't get iptables-restore version; assuming it doesn't support --wait: \"executable file not found in $PATH\""
May 24 15:48:30 node01 crio[217790]: time="2025-05-24T15:48:30.757957989+02:00" level=warning msg="Error checking iptables version, assuming version at least: executable file not found in $PATH (version=\"1.4.11\>
May 24 15:48:30 node01 crio[217790]: time="2025-05-24T15:48:30.739755963+02:00" level=warning msg="Couldn't get iptables-restore version; assuming it doesn't support --wait: \"executable file not found in $PATH\""
May 24 15:48:30 node01 crio[217790]: time="2025-05-24T15:48:30.73972771+02:00" level=warning msg="Error checking iptables version, assuming version at least: executable file not found in $PATH (version=\"1.4.11\">
```

</details>

stacktrace - https://gist.github.com/trexx/9c9be48de50f393d8456ec4aa07b7287

It maybe possible I've been too eager to update?

### What did you expect to happen?

The pod terminates and crio continues to run.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: default
spec:
  containers:
  - image: hello-world:latest
    imagePullPolicy: IfNotPresent
    name: hello-world
    ports:
    - containerPort: 80
      hostPort: 80
      name: http
      protocol: TCP
```

### Anything else we need to know?

_No response_

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.33.0
   GitCommit:      9d143f94054fc5c8338673f35f7c0164490363b3
   GitCommitDate:  2025-05-15T18:26:05Z
   GitTreeState:   dirty
   BuildDate:      1970-01-01T00:00:00Z
   GoVersion:      go1.24.2
   Compiler:       gc
   Platform:       linux/amd64
   Linkmode:       static
   BuildTags:
     static
     netgo
     osusergo
     exclude_graphdriver_btrfs
     seccomp
     apparmor
     selinux
   LDFlags:          unknown
   SeccompEnabled:   true
   AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
Client Version: v1.32.4
Kustomize Version: v5.5.0
Server Version: v1.33.1+k0s
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="42 (Adams)"
RELEASE_TYPE=stable
ID=fedora
VERSION_ID=42
VERSION_CODENAME=""
PLATFORM_ID="platform:f42"
PRETTY_NAME="Fedora Linux 42 (Adams)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:42"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f42/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=42
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=42
SUPPORT_END=2026-05-13

$ uname -a
Linux snake 6.14.6-300.fc42.x86_64 #1 SMP PREEMPT_DYNAMIC Fri May  9 20:11:19 UTC 2025 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

Physical box running Intel N100, 32GB RAM, 1TB NVME
Cilium 1.17.4
Crun 1.21

### PR DESCRIPTION
**Pull request by danwinship**
The new iptables-and-nftables MetaHostPortManager code was falling victim to a classic golang gotcha. If `newHostportManagerIPTables` returned a `nil` value (of type `*hostportManagerIPTables`), then that value would get assigned to `mh.managers[utilnet.IPv4].iptables`, but that value is a `HostPortManager`, so the value would be typecast, becoming a non-`nil` `HostPortManager` value wrapping the `nil` `*hostportManagerIPTables` value, and then later, this code

https://github.com/cri-o/cri-o/blob/9d143f94054fc5c8338673f35f7c0164490363b3/internal/hostport/meta_hostport_manager.go#L143-L149

would see that it was non-`nil` and attempt to call a method on it, which would then SEGV because the underlying `*hostportManagerIPTables` was `nil`.

There are a few possible ways to fix this... this is one of them... 

This wasn't caught by unit tests because the unit tests don't use `NewMetaHostportManager` (since it's not fully mock-able) and it wasn't caught by e2e tests because the e2e environment has both iptables and nftables installed.

I also pulled in a cri-o-ified version of [kubernetes/kubernetes@`b031258`](https://github.com/kubernetes/kubernetes/pull/129826/commits/b03125896923d59a2d12a17e16d6289be9fce6e8) to get rid of the superfluous error messages also seen in #9220.

Fixes #9220
/kind bug
/kind cleanup

#### Does this PR introduce a user-facing change?
```release-note
Fixes a crash introduced in 1.33.0 when cleaning up a pod that uses HostPorts
on a system that has either just iptables (but not nftables) or just nftables
(but not iptables).
```

### CODE REVIEW

File: internal/iptables/iptables.go [hunk 1]
```diff
@@ -237,14 +231,22 @@ func newInternal(ctx context.Context, exec utilexec.Interface, protocol Protocol
...
 		lockfilePath16x: lockfilePath16x,
 	}
 
+	version, err := getIPTablesVersion(exec, protocol)
+	if err != nil {
+		// The only likely error is "no such file or directory", in which case any
+		// further commands will fail the same way, so we don't need to do
+		// anything special here.
+		return runner
+	}
```
Comment (bitoku) [inline internal/iptables/iptables.go:244]: I might be too sensitive, but I want to log something every time we get error, especially when it interacts with something not managed by us.
But debug log is enough, I think.

**Comment by bitoku** [comment]
Thank you for the quick fix!

**Comment by haircommander** [comment]
/approve

thank you for the quick fix!
